Add parameter to load specific forms in read_redcap_tidy
CHOP-CGTDataOps/REDCapTidieR pull request #43
Opened 2022-09-30 20:20 UTC by ezraporter

# Description
This PR implements a feature allowing users to specify which forms to download from a REDCap project. If the user specifies any forms that don't exist in the project an informative error message is given.

I also confirmed that this plays well with our check for forms that the user doesn't have access to. If a user requests a form they don't have access to in `forms` they'll get a warning from `check_user_rights()` (same as before). If they specify only forms that they have access to they won't get a warning.

# Proposed Changes 

- Add `forms` parameter to `read_redcap_tidy()` to be passed through to `REDCapR::read_redcap_oneshot()`
- Check argument to `forms` to ensure all forms exist in the project metadata

### Issue Addressed
Closes #36

### PR Checklist
Before submitting this PR, please check and verify below that the submission meets the below criteria:

- [ ] New/revised functions have associated tests
- [ ] New/revised functions use appropriate naming conventions
- [ ] New/revised functions don't repeat code
- [ ] Code changes are less than **250** lines total
- [ ] Issues linked to the PR using [GitHub's list of keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] The appropriate reviewer is assigned to the PR
- [ ] The appropriate developers are assigned to the PR

# Code Review
This section to be used by the reviewer and developers during Code Review after PR submission

### Code Review Checklist

- [ ] I checked that new files follow naming conventions and are in the right place
- [ ] I checked that documentation is complete, clear, and without typos
- [ ] I added/edited comments to explain "why" not "how"
- [ ] I checked that all new variable and function names follow naming conventions
- [ ] I checked that new tests have been written for key business logic and/or bugs that this PR fixes
- [ ] I checked that new tests address important edge cases

2022-10-01 14:14 UTC, skadauke requested changes
This looks great! Would suggest implementing the error message using CLI.

2022-10-02 23:12 UTC, rsh52 commented on R/checks.R
> +  if (length(missing_forms) > 0) {
`cli` looks great, powerful and also aesthetically engaging. 

Should we implement `cli` to just the error message for this PR, to all messages, or separate this feature implementation and then apply `cli` in a separate PR?

2022-10-02 23:14 UTC, rsh52 reviewed
I think all of the changes look great, once we decide how/where to implement `cli` should be good to go!

We also have to add @ezraporter to our author list!

2022-10-03 01:32 UTC, skadauke commented
> I think all of the changes look great, once we decide how/where to implement `cli` should be good to go!

I would say, let's implement it here, then create an Issue to implement it throughout?

> We also have to add @ezraporter to our author list!

Yes we do!!

2022-10-03 19:08 UTC, ezraporter commented
I've updated the error message to use `cli`:

```r
devtools::load_all()

classic_token <- Sys.getenv("REDCAPTIDIER_CLASSIC_API")
redcap_uri <- Sys.getenv("REDCAP_URI")

read_redcap_tidy(redcap_uri,
                 classic_token,
                 forms = "fake-form")
```

![cli](https://user-images.githubusercontent.com/60618324/193656260-0d55c37e-c320-4af7-9453-581412f568d6.png)

Since we're implicitly using `rlang` to issue this error I followed the [Advanced R idea](https://adv-r.hadley.nz/conditions.html#custom-conditions) of adding custom classes to our error:

```r
# Catch the error
e <- tryCatch({
  read_redcap_tidy(redcap_uri,
                   classic_token,
                   forms = "fake-form")
  }, error = function(e) e)

class(e)
#> [1] "form_does_not_exist" "REDCapTidieR_cond" "rlang_error" "error"              
#> [5] "condition"
```

`form_does_not_exist` is specific to this error and the idea would be for `REDCapTidieR_cond` to identify conditions issued by the package in general.

2022-10-03 22:42 UTC, skadauke commented
I love the idea of creating custom condition classes using `cli_abort` and then `expect`ing them in the tests!

2022-10-03 22:44 UTC, skadauke approved these changes
Looks great to me!

2022-10-04 12:15 UTC, rsh52 approved these changes
Love it, very succinct and nicely done.

2022-10-04 15:12 UTC, merged